import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import SideBar from '@/components/organisms/SideBar';
import AmplifyClientProvider from '@/components/atoms/AmplifyClientProvider';
import '@aws-amplify/ui-react/styles.css';
import LoadingState from '@/components/atoms/LoadingState';
import QueryProvider from '@/providers/QueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='h-full w-full'>
      <body
        className={cn(
          inter.className,
          'flex h-full w-full justify-center overflow-hidden bg-slate-700'
        )}
      >
        <AmplifyClientProvider>
          <QueryProvider>
            <SideBar />
            <div className='relative h-full w-full flex-col overflow-auto'>
              <LoadingState />
              {children}
            </div>
          </QueryProvider>
        </AmplifyClientProvider>
      </body>
    </html>
  );
}
